# Generated by Django 4.2 on 2023-05-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_rename_apellido_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contraseñas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
