# Generated by Django 4.2 on 2023-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_contraseña_usuario_contraseñas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='email',
            new_name='email15',
        ),
        migrations.RemoveField(
            model_name='vendedor_certificado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='vendedor_certificado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendedor_certificado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='vendedor_promocionado',
            name='email',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email0',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendedor_certificado',
            name='DNI1',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='vendedor_certificado',
            name='apellido1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendedor_certificado',
            name='email1',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendedor_certificado',
            name='nombre1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendedor_certificado',
            name='nombre_d_usuario1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendedor_promocionado',
            name='DNI',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='vendedor_promocionado',
            name='Promo_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vendedor_promocionado',
            name='email2',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendedor_promocionado',
            name='nombre_d_usuario',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseñas',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_d_usuario',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor_promocionado',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='vendedor_promocionado',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
