# Generated by Django 4.2 on 2023-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_vendedor_certificado_dni1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor_certificado',
            name='DNI1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendedor_promocionado',
            name='DNI',
            field=models.IntegerField(default=0),
        ),
    ]
