# Generated by Django 4.2 on 2023-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_vendedor_certificado_dni1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor_certificado',
            name='DNI1',
            field=models.CharField(default='', max_length=30),
        ),
    ]
